export enum TranslatedKeysStandart {
  "Код товара" = "codeOfItem",
  "Тип" = "type",
  "Производитель" = "nameOfBrand",
  "Состояние" = "condition",
  "Страна производства" = "country",
  "Форма корпуса" = "bodyShape",
  "Ориентация" = "orientation",
  "Количество струн" = "valueOfStrings",
  "Количество ладов" = "valueOfFrets",
  "Мензура, дюймов" = "widthOfUpperSill",
  "Дека" = "deck",
  "Гриф" = "neck",
  "Накладка на гриф" = "fingerboard",
  "Цвет корпуса" = "colorOfBody",
  "Электроника" = "electronics",
  "Звукосниматели" = "pickupsSchema",
  "Бридж" = "bridge",
  "Крепление грифа" = "fixingNeck",
  "Артикул" = "article",
  "Вес" = "weight",
  "Верхняя дека" = "upperDeck",
  "Нижняя дека" = "lowerDeck",
  "Вырез на корпусе" = "cotoutOfBody",
  "Обечайка" = "shell",
  "Верхняя дека из массива" = "upperDeckIsSolidWood",
  "Нижняя дека из массива" = "lowerDeckIsSolidWood",
  "Ширина верхнего порожка, мм" = "widthOfUpperThreshold",
  "Струны" = "typeOfStrings",
  "В комплекте" = "included",
  "Серия" = "series",
  "Страна бренда" = "countryOfBrand",
}

export enum TranslatedKeysStrings {
  "Код товара" = "codeOfItem",
  "Тип" = "type",
  "Производитель" = "nameOfBrand",
  "Серия" = "series",
  "Состояние" = "condition",
  "Страна производства" = "country",
  "Количество комплектов" = "countOfSets",
  "Количество струн" = "valueOfStrings",
  "Размер набора струн" = "sizeOfSet",
  "Материал струн" = "material",
  "Натяжение" = "tension",
  "Шарик на конце" = "ballOfEndStrings",
  "Защитное полимерное покрытие" = "polymerCoating",
  "Калибр струны" = "caliberOfString",
  "Тип оплётки" = "typeOfBraid",
  "Артикул" = "article",
  "Вес" = "weight",
}
